

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    upload_to_play_store(
      track: 'internal'
    )
  end
end
